# Generated by Django 5.0.7 on 2024-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
